services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
    ports:
      - 8191:8191
    restart: unless-stopped 

  prowlarr:
    depends_on:
      - flaresolverr
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - ./data/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  downloader:
    image: rogerfar/rdtclient
    container_name: downloader
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - ./data/rdtclient:/data/db
      - /media/downloads:/data/downloads
    logging:
       driver: json-file
       options:
          max-size: 10m
    ports:
      - 6500:6500
    restart: unless-stopped

  radarr:
    depends_on:
      - downloader
      - prowlarr
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - ./data/radarr:/config
      - /media/movies:/movies
      - /media/downloads/radarr:/media/downloads/radarr
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    depends_on:
      - downloader
      - prowlarr
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - ./data/sonarr:/config
      - /media/anime:/series
      - /media/downloads/sonarr:/media/downloads/sonarr
    ports:
      - 8989:8989
    restart: unless-stopped
